<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.gencode</groupId>
        <artifactId>gencode-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>gencode-module-system</artifactId>
    <name>gencode-module-system</name>
    <description>系统模块：用户/角色/菜单/部门/租户/字典/参数/日志/仪表盘</description>

    <dependencies>
        <dependency>
            <groupId>com.gencode</groupId>
            <artifactId>gencode-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>
    </dependencies>
</project>
